name: Build DigitalCredentials Sample

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.4.0
        with:
          persist-credentials: false

      - name: Set Up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.9.1
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f7112c0b10625dcfba7206fa19e6b3bcbd1e52e4 # v4.4.4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./DigitalCredentials

      - name: Build DigitalCredentials app
        working-directory: ./DigitalCredentials
        run: ./gradlew app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.0
        with:
          name: digital-credentials-debug-apk
          path: DigitalCredentials/app/build/outputs/apk/debug/app-debug.apk
