name: Build DigitalCredentials Sample

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e5c1d636b0051e5e01614e59f49352e61a681d4e # v4.4.0
        with:
          persist-credentials: false

      - name: Set Up JDK
        uses: actions/setup-java@cf277c64a78058e8d562245c9284342f0a1458e6 # v4.9.1
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af54316d24a737402660d1b54a0558197771746f # v4.4.4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./DigitalCredentials

      - name: Build DigitalCredentials app
        working-directory: ./DigitalCredentials
        run: ./gradlew app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@834a1448b96a335756a79f0697d62057f8974a21 # v4.4.0
        with:
          name: digital-credentials-debug-apk
          path: DigitalCredentials/app/build/outputs/apk/debug/app-debug.apk
